name: plato_perfecto
description: "Flutter project for Hiberus University by Belén Grande."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_hooks: ^0.20.3
  flutter_signin_button: ^2.0.0
  form_field_validator: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_flushbar: ^0.0.2
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  go_router: ^12.1.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #