name: plato_perfecto
description: "Flutter project for Hiberus University by Belén Grande."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_hooks: ^0.20.3
  flutter_signin_button: ^2.0.0
  form_field_validator: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_flushbar: ^0.0.2
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  go_router: ^12.1.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  firebase_database: ^10.3.8
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.1
  uuid: ^4.2.2
  dio: ^5.4.0
  get_it: ^7.6.6
  loading_view: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: LindenHill
      fonts:
        - asset: assets/fonts/Linden_Hill/LindenHill-Regular.ttf
        - asset: assets/fonts/Linden_Hill/LindenHill-Italic.ttf
          style: italic
