// To parse this JSON data, do
//
//     final recipe = recipeFromMap(jsonString);

class Recipe {
    String idMeal;
    String strMeal;
    String strCategory;
    String strInstructions;
    String strIngredient1;
    String strIngredient2;
    String strIngredient3;
    String strIngredient4;
    String strIngredient5;
    String strIngredient6;
    String strIngredient7;
    String strIngredient8;
    String strIngredient9;
    String strIngredient10;
    String strIngredient11;
    String strIngredient12;
    String strIngredient13;
    String strIngredient14;
    String strIngredient15;
    dynamic strIngredient16;
    dynamic strIngredient17;
    dynamic strIngredient18;
    dynamic strIngredient19;
    dynamic strIngredient20;
    String strMeasure1;
    String strMeasure2;
    String strMeasure3;
    String strMeasure4;
    String strMeasure5;
    String strMeasure6;
    String strMeasure7;
    String strMeasure8;
    String strMeasure9;
    String strMeasure10;
    String strMeasure11;
    String strMeasure12;
    String strMeasure13;
    String strMeasure14;
    String strMeasure15;
    dynamic strMeasure16;
    dynamic strMeasure17;
    dynamic strMeasure18;
    dynamic strMeasure19;
    dynamic strMeasure20;
    dynamic strSource;
    dynamic strMealThumb;

    Recipe({
        required this.idMeal,
        required this.strMeal,
        required this.strCategory,
        required this.strInstructions,
        required this.strIngredient1,
        required this.strIngredient2,
        required this.strIngredient3,
        required this.strIngredient4,
        required this.strIngredient5,
        required this.strIngredient6,
        required this.strIngredient7,
        required this.strIngredient8,
        required this.strIngredient9,
        required this.strIngredient10,
        required this.strIngredient11,
        required this.strIngredient12,
        required this.strIngredient13,
        required this.strIngredient14,
        required this.strIngredient15,
        required this.strIngredient16,
        required this.strIngredient17,
        required this.strIngredient18,
        required this.strIngredient19,
        required this.strIngredient20,
        required this.strMeasure1,
        required this.strMeasure2,
        required this.strMeasure3,
        required this.strMeasure4,
        required this.strMeasure5,
        required this.strMeasure6,
        required this.strMeasure7,
        required this.strMeasure8,
        required this.strMeasure9,
        required this.strMeasure10,
        required this.strMeasure11,
        required this.strMeasure12,
        required this.strMeasure13,
        required this.strMeasure14,
        required this.strMeasure15,
        required this.strMeasure16,
        required this.strMeasure17,
        required this.strMeasure18,
        required this.strMeasure19,
        required this.strMeasure20,
        required this.strSource,
        required this.strMealThumb,
    });
}
