// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkeA_0KOayT1BFrUcbbAZBWlnHKfX9mPU',
    appId: '1:1049156752358:web:aa7d3b389ace7867e4fc27',
    messagingSenderId: '1049156752358',
    projectId: 'plato-perfecto',
    authDomain: 'plato-perfecto.firebaseapp.com',
    storageBucket: 'plato-perfecto.appspot.com',
    measurementId: 'G-6LVFG1TM22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8eto-2c0SF4EegvFAchPwz3pG6Db2GpY',
    appId: '1:1049156752358:android:127506d859a94363e4fc27',
    messagingSenderId: '1049156752358',
    projectId: 'plato-perfecto',
    storageBucket: 'plato-perfecto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2SifGMWgHreC1x0jmZl5MwfsYvUdVuw',
    appId: '1:1049156752358:ios:13c5f4f49782f6eae4fc27',
    messagingSenderId: '1049156752358',
    projectId: 'plato-perfecto',
    storageBucket: 'plato-perfecto.appspot.com',
    iosClientId: '1049156752358-u9930h8gulpcmip7p48r21c6s1dic04f.apps.googleusercontent.com',
    iosBundleId: 'com.example.platoPerfecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2SifGMWgHreC1x0jmZl5MwfsYvUdVuw',
    appId: '1:1049156752358:ios:1ce95a30f7c6ca90e4fc27',
    messagingSenderId: '1049156752358',
    projectId: 'plato-perfecto',
    storageBucket: 'plato-perfecto.appspot.com',
    iosClientId: '1049156752358-b193mpvtppm08jlijmg1uc6i70kjdid3.apps.googleusercontent.com',
    iosBundleId: 'com.example.platoPerfecto.RunnerTests',
  );
}
